#include <bits/stdc++.h>

using namespace std;

vector <string> v;

void fill_arr()
{
    v.push_back("RGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBY");
    v.push_back("RGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYB");
    v.push_back("RYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGB");
    v.push_back("RYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBG");
    v.push_back("RBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYG");
    v.push_back("RBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGY");
    
    v.push_back("GRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBY");
    v.push_back("GRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYB");
    v.push_back("GYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRB");
    v.push_back("GYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBR");
    v.push_back("GBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYR");
    v.push_back("GBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRY");

    v.push_back("BRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGY");
    v.push_back("BRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYG");
    v.push_back("BYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRG");
    v.push_back("BYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGR");
    v.push_back("BGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYR");
    v.push_back("BGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRY");

    v.push_back("YRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGBYRGB");
    v.push_back("YRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBGYRBG");
    v.push_back("YBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRGYBRG");
    v.push_back("YBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGRYBGR");
    v.push_back("YGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBRYGBR");
    v.push_back("YGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRBYGRB");
}

int main()
{
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);

    string s, vs;
    int i, j, f, len;
    map <char, int> mp;

    mp.insert(make_pair('R', 0));
    mp.insert(make_pair('B', 0));
    mp.insert(make_pair('G', 0));
    mp.insert(make_pair('Y', 0));

    fill_arr();

    cin >> s;

    len = (int) s.size();

    for (i = 0; i < 24; i++) {
        f = 1;

        for (j = 0; j < len; j++) {
            if (s[j] != '!' && v[i][j] != s[j]) {
                f = 0;

                break;
            }
        }

        if (f == 1) {
            vs = v[i];

            break;
        }
    }

    while (vs.size() < s.size()) {
        vs += v[i];
    }

    for (i = 0; i < s.size(); i++) {
        if (s[i] == '!') {
            mp[vs[i]]++;
        }
    }

    auto it = mp.begin();

    int b = (*it).second; 
    it++;
    int g = (*it).second; 
    it++;
    int r = (*it).second; 
    it++;
    int y = (*it).second;

    cout << r << " " << b << " " << y << " " << g;

    return 0;
}